services:
  db:
    image: timescale/timescaledb:2.17.0-pg16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - counter_app_deployment_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    # ports:
    #   - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}

  tracer:
    image: jaegertracing/all-in-one:1.60
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 14250:14250
      - 14268:14268
      - 14269:14269

  frontend:
    image: 11.12.10.8:5000/counter/frontend

  user_access_control:
    image: 11.12.10.8:5000/counter/user_access_control
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVICE_NAME=[COUNTER-APP]USER-ACCESS-CONTROL
      - PORT=8000
      - DEBUG=true
      - HASHIDS_SALT=7nicwCviyx5UMslJ4gzoYHHtLAiGZXcf
      - OTEL_EXPORTER_OTLP_ENDPOINT=tracer:4317
      - DB_USER=COUNTER@2024
      - DB_PASS=counter_admin_2024
      - DB_NAME=user_access_control_db
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - REDIS_DB=0

  counter:
    image: 11.12.10.8:5000/counter/counter-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/__ready"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVICE_NAME=[COUNTER-APP]COUNTER-SERVICE
      - PORT=8001
      - DEBUG=true
      - HASHIDS_SALT=7nicwCviyx5UMslJ4gzoYHHtLAiGZXcf
      - OTEL_EXPORTER_OTLP_ENDPOINT=tracer:4317
      - DB_USER=COUNTER@2024
      - DB_PASS=counter_admin_2024
      - DB_NAME=counter_db
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - REDIS_DB=0

  gateway:
    image: "nginx"
    restart: unless-stopped
    # depends_on:
    #   user_access_control:
    #     condition: service_healthy
    #   counter:
    #     condition: service_healthy
    ports:
      - "4080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  counter_app_deployment_db:
    external: true
